import "dotenv/config";

export const env = {
  nodeEnv: process.env.NODE_ENV ?? "development",
  port: Number(process.env.PORT ?? process.env.API_PORT ?? 4000),
  corsOrigin: process.env.CORS_ORIGIN ?? "http://localhost:3000",
  databaseUrl: process.env.DATABASE_URL ?? "",
  redisUrl: process.env.REDIS_URL ?? "redis://localhost:6379",
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET ?? "access_secret",
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET ?? "refresh_secret",
  jwtAccessTtl: process.env.JWT_ACCESS_TTL ?? "15m",
  jwtRefreshTtl: process.env.JWT_REFRESH_TTL ?? "30d",
  otpProvider: process.env.OTP_PROVIDER ?? "real",
  otpSmsProvider: process.env.OTP_SMS_PROVIDER ?? "twilio",
  otpEmailProvider: process.env.OTP_EMAIL_PROVIDER ?? "resend",
  otpSenderName: process.env.OTP_SENDER_NAME ?? "KongoLove",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? "",
  twilioFrom: process.env.TWILIO_FROM ?? "",
  vonageApiKey: process.env.VONAGE_API_KEY ?? "",
  vonageApiSecret: process.env.VONAGE_API_SECRET ?? "",
  vonageFrom: process.env.VONAGE_FROM ?? "KongoLove",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
  sendgridApiKey: process.env.SENDGRID_API_KEY ?? "",
  sendgridFromEmail: process.env.SENDGRID_FROM_EMAIL ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: Number(process.env.SMTP_PORT ?? 587),
  smtpSecure: (process.env.SMTP_SECURE ?? "false") === "true",
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPass: process.env.SMTP_PASS ?? "",
  smtpFromEmail: process.env.SMTP_FROM_EMAIL ?? "",
  oauthGoogleClientId: process.env.OAUTH_GOOGLE_CLIENT_ID ?? "",
  oauthGoogleClientSecret: process.env.OAUTH_GOOGLE_CLIENT_SECRET ?? "",
  oauthGoogleRedirectUri: process.env.OAUTH_GOOGLE_REDIRECT_URI ?? "",
  oauthAppleClientId: process.env.OAUTH_APPLE_CLIENT_ID ?? "",
  oauthAppleTeamId: process.env.OAUTH_APPLE_TEAM_ID ?? "",
  oauthAppleKeyId: process.env.OAUTH_APPLE_KEY_ID ?? "",
  oauthApplePrivateKey: process.env.OAUTH_APPLE_PRIVATE_KEY ?? "",
  oauthAppleRedirectUri: process.env.OAUTH_APPLE_REDIRECT_URI ?? "",
  oauthFrontendSuccessUrl: process.env.OAUTH_FRONTEND_SUCCESS_URL ?? `${process.env.CORS_ORIGIN ?? "http://localhost:3000"}/auth/social-success`,
  mediaProvider: process.env.MEDIA_PROVIDER ?? "cloudinary",
  paymentWebhookSecret: process.env.PAYMENT_WEBHOOK_SECRET ?? "dev_payment_webhook_secret",
  mmAirtelApiUrl: process.env.MM_AIRTEL_API_URL ?? "",
  mmAirtelApiToken: process.env.MM_AIRTEL_API_TOKEN ?? "",
  mmOrangeApiUrl: process.env.MM_ORANGE_API_URL ?? "",
  mmOrangeApiToken: process.env.MM_ORANGE_API_TOKEN ?? "",
  mmMPesaApiUrl: process.env.MM_MPESA_API_URL ?? "",
  mmMPesaApiToken: process.env.MM_MPESA_API_TOKEN ?? "",
  mmAfricellApiUrl: process.env.MM_AFRICELL_API_URL ?? "",
  mmAfricellApiToken: process.env.MM_AFRICELL_API_TOKEN ?? "",
  mmAfrimoneyApiUrl: process.env.MM_AFRIMONEY_API_URL ?? "",
  mmAfrimoneyApiToken: process.env.MM_AFRIMONEY_API_TOKEN ?? "",
  webPushVapidPublicKey: process.env.WEB_PUSH_VAPID_PUBLIC_KEY ?? "",
  webPushVapidPrivateKey: process.env.WEB_PUSH_VAPID_PRIVATE_KEY ?? "",
  superAdminEmail: process.env.SUPERADMIN_EMAIL ?? "",
  superAdminPhone: process.env.SUPERADMIN_PHONE ?? "",
  superAdminPassword: process.env.SUPERADMIN_PASSWORD ?? ""
};
